# Generated by Django 5.2.8 on 2025-11-19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        # No dependencies - this must run first
    ]

    operations = [
        migrations.RunSQL(
            sql="CREATE EXTENSION IF NOT EXISTS vector;",
            reverse_sql="DROP EXTENSION IF EXISTS vector;",
        ),
    ]

