# Generated by Django 5.2.8 on 2025-11-18 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="documentchunk",
            name="token_count",
            field=models.IntegerField(default=0),
        ),
    ]
