# Generated by Django 5.2.8 on 2025-11-19

from django.db import migrations


def delete_orphaned_documents(apps, schema_editor):
    """Delete documents with user=None (test data)"""
    Document = apps.get_model('app', 'Document')
    Document.objects.filter(user__isnull=True).delete()


def reverse_delete_orphaned_documents(apps, schema_editor):
    """Reverse operation - nothing to do"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_documentchunk_token_count"),
    ]

    operations = [
        migrations.RunPython(
            delete_orphaned_documents,
            reverse_delete_orphaned_documents
        ),
    ]

