# Generated by Django 5.2.8 on 2025-11-19

import django.db.models.deletion
import pgvector.django.vector
from django.conf import settings
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_delete_orphaned_documents"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Step 1: Create ChatSession model
        migrations.CreateModel(
            name="ChatSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_id", models.CharField(max_length=255, unique=True)),
                ("title", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "system_prompt",
                    models.TextField(
                        default="You are a helpful assistant. Answer questions based on the user's uploaded documents."
                    ),
                ),
                (
                    "model_provider",
                    models.CharField(
                        choices=[
                            ("openai", "OpenAI"),
                            ("anthropic", "Anthropic"),
                            ("ollama", "Ollama"),
                        ],
                        default="ollama",
                        max_length=50,
                    ),
                ),
                ("model_name", models.CharField(default="llama3.1", max_length=100)),
                (
                    "temperature",
                    models.DecimalField(decimal_places=2, default=0.7, max_digits=3),
                ),
                ("max_tokens", models.IntegerField(default=2000)),
                ("max_context_tokens", models.IntegerField(default=4000)),
                ("metadata", models.JSONField(default=dict)),
                ("message_count", models.IntegerField(default=0)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("last_message_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chat_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Chat Session",
                "verbose_name_plural": "Chat Sessions",
                "db_table": "chat_sessions",
                "ordering": ["-last_message_at", "-started_at"],
            },
        ),
        
        # Step 3: Add new fields to Document
        migrations.AddField(
            model_name="document",
            name="category",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="document",
            name="tags",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="document",
            name="metadata",
            field=models.JSONField(default=dict),
        ),
        
        # Step 4: Update Document.user to CASCADE and non-nullable
        migrations.AlterField(
            model_name="document",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="documents",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        
        # Step 5: Make file_hash unique
        migrations.AlterField(
            model_name="document",
            name="file_hash",
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        
        # Step 6: Add indexes to Document
        migrations.AddIndex(
            model_name="document",
            index=models.Index(fields=["user", "status"], name="documents_user_status_idx"),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(fields=["user", "created_at"], name="documents_user_created_idx"),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(fields=["file_hash"], name="documents_file_hash_idx"),
        ),
        
        # Step 7: Update ChatMessage - add session FK
        migrations.AddField(
            model_name="chatmessage",
            name="session",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="messages",
                to="app.chatsession",
            ),
        ),
        
        # Step 8: Update ChatMessage role choices
        migrations.AlterField(
            model_name="chatmessage",
            name="role",
            field=models.CharField(
                choices=[
                    ("user", "User"),
                    ("assistant", "Assistant"),
                    ("system", "System"),
                ],
                max_length=20,
            ),
        ),
        
        # Step 9: Add analytics fields to ChatMessage
        migrations.AddField(
            model_name="chatmessage",
            name="tokens_used",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="chatmessage",
            name="model_used",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="chatmessage",
            name="response_time_ms",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="chatmessage",
            name="sources",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="chatmessage",
            name="metadata",
            field=models.JSONField(default=dict),
        ),
        
        # Step 10: Add indexes to ChatMessage
        migrations.AddIndex(
            model_name="chatmessage",
            index=models.Index(fields=["session", "created_at"], name="chat_messages_session_created_idx"),
        ),
        migrations.AddIndex(
            model_name="chatmessage",
            index=models.Index(fields=["document", "created_at"], name="chat_messages_document_created_idx"),
        ),
        migrations.AddIndex(
            model_name="chatmessage",
            index=models.Index(fields=["user", "created_at"], name="chat_messages_user_created_idx"),
        ),
        
        # Step 11: Add indexes to ChatSession
        migrations.AddIndex(
            model_name="chatsession",
            index=models.Index(fields=["user", "last_message_at"], name="chat_sessions_user_last_msg_idx"),
        ),
        migrations.AddIndex(
            model_name="chatsession",
            index=models.Index(fields=["session_id"], name="chat_sessions_session_id_idx"),
        ),
    ]
