# Generated by Django 5.2.8 on 2025-11-20 07:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0005_enable_pgvector_extension"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="chatsession",
            options={"ordering": ["-last_message_at", "-started_at"]},
        ),
        migrations.RenameIndex(
            model_name="chatmessage",
            new_name="chat_messag_session_597c4e_idx",
            old_name="chat_messages_session_created_idx",
        ),
        migrations.RenameIndex(
            model_name="chatmessage",
            new_name="chat_messag_documen_a6d76d_idx",
            old_name="chat_messages_document_created_idx",
        ),
        migrations.RenameIndex(
            model_name="chatmessage",
            new_name="chat_messag_user_id_ecc172_idx",
            old_name="chat_messages_user_created_idx",
        ),
        migrations.RenameIndex(
            model_name="chatsession",
            new_name="chat_sessio_user_id_d1221f_idx",
            old_name="chat_sessions_user_last_msg_idx",
        ),
        migrations.RenameIndex(
            model_name="chatsession",
            new_name="chat_sessio_session_a3bcba_idx",
            old_name="chat_sessions_session_id_idx",
        ),
        migrations.RenameIndex(
            model_name="document",
            new_name="documents_user_id_10766e_idx",
            old_name="documents_user_status_idx",
        ),
        migrations.RenameIndex(
            model_name="document",
            new_name="documents_user_id_b94ad8_idx",
            old_name="documents_user_created_idx",
        ),
        migrations.RenameIndex(
            model_name="document",
            new_name="documents_file_ha_3bbf78_idx",
            old_name="documents_file_hash_idx",
        ),
        migrations.AddField(
            model_name="chatsession",
            name="document",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chat_sessions",
                to="app.document",
            ),
        ),
        migrations.AlterField(
            model_name="chatsession",
            name="system_prompt",
            field=models.TextField(
                default="You are a helpful assistant. Answer questions clearly and comprehensively. When the user asks about their uploaded documents, use the provided context. For general questions, use your knowledge to provide helpful answers."
            ),
        ),
        migrations.AddIndex(
            model_name="chatsession",
            index=models.Index(
                fields=["document", "user"], name="chat_sessio_documen_8d585e_idx"
            ),
        ),
    ]
